<?php

/**
 * Canonical flat → grouped v2 mapping for settings. Single source for Adapter and schema export.
 *
 * @package Modula
 */

namespace Modula\V2\Settings;

defined( 'ABSPATH' ) || exit;

/**
 * Class Field_Registry
 */
class Field_Registry {


	/**
	 * Flat key => [ group, key ]. Key is the grouped schema key (camelCase).
	 *
	 * @var array<string, array{group: string, key: string}>
	 * @phpcs:disable WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound, WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned
	 */
	private static $flat_to_grouped = array(
		'type' => array( 'group' => 'general', 'key' => 'type' ),
		'upload_position' => array( 'group' => 'general', 'key' => 'uploadPosition' ),
		'width' => array( 'group' => 'general', 'key' => 'width' ),
		'height' => array( 'group' => 'general', 'key' => 'height' ),
		'randomFactor' => array( 'group' => 'general', 'key' => 'randomFactor' ),
		'shuffle' => array( 'group' => 'general', 'key' => 'shuffle' ),
		'grid_type' => array( 'group' => 'layout', 'key' => 'gridType' ),
		'uniform_grid_tile_aspect' => array( 'group' => 'layout', 'key' => 'uniformGridTileAspect' ),
		'uniform_grid_tile_aspect_custom' => array( 'group' => 'layout', 'key' => 'uniformGridTileAspectCustom' ),
		'fit_grid_image_align' => array( 'group' => 'layout', 'key' => 'fitGridImageAlign' ),
		'grid_row_height' => array( 'group' => 'layout', 'key' => 'gridRowHeight' ),
		'grid_justify_last_row' => array( 'group' => 'layout', 'key' => 'gridJustifyLastRow' ),
		'grid_image_size' => array( 'group' => 'layout', 'key' => 'gridImageSize' ),
		'grid_image_dimensions' => array( 'group' => 'layout', 'key' => 'gridImageDimensions' ),
		'img_size' => array( 'group' => 'layout', 'key' => 'imgSize' ),
		'img_crop' => array( 'group' => 'layout', 'key' => 'imgCrop' ),
		'grid_image_crop' => array( 'group' => 'layout', 'key' => 'gridImageCrop' ),
		'gutter' => array( 'group' => 'layout', 'key' => 'gutter' ),
		'tablet_gutter' => array( 'group' => 'layout', 'key' => 'tabletGutter' ),
		'mobile_gutter' => array( 'group' => 'layout', 'key' => 'mobileGutter' ),
		'parallax_overlay_enabled' => array( 'group' => 'layout', 'key' => 'parallaxOverlayEnabled' ),
		'parallax_overlay_background' => array( 'group' => 'layout', 'key' => 'parallaxOverlayBackground' ),
		'parallax_caption' => array( 'group' => 'layout', 'key' => 'parallaxCaption' ),
		'parallax_motion_preset' => array( 'group' => 'layout', 'key' => 'parallaxMotionPreset' ),
		'lightbox' => array( 'group' => 'lightbox', 'key' => 'lightbox' ),
		'lightbox_click_not_lightbox_hint' => array( 'group' => 'lightbox', 'key' => 'clickNotLightboxHint' ),
		'show_navigation' => array( 'group' => 'lightbox', 'key' => 'showNavigation' ),
		'open_Lightbox_on' => array( 'group' => 'lightbox', 'key' => 'openOn' ),
		'doubleClick' => array( 'group' => 'lightbox', 'key' => 'doubleClick' ),
		'loop_lightbox' => array( 'group' => 'lightbox', 'key' => 'loop' ),
		'showTitleLightbox' => array( 'group' => 'lightbox', 'key' => 'showTitle' ),
		'showCaptionLightbox' => array( 'group' => 'lightbox', 'key' => 'showCaption' ),
		'captionPosition' => array( 'group' => 'lightbox', 'key' => 'captionPosition' ),
		'lightbox_keyboard' => array( 'group' => 'lightbox', 'key' => 'keyboard' ),
		'lightbox_wheel' => array( 'group' => 'lightbox', 'key' => 'wheel' ),
		'lightbox_toolbar' => array( 'group' => 'lightbox', 'key' => 'toolbar' ),
		'lightbox_toolbar_off_hint' => array( 'group' => 'lightbox', 'key' => 'toolbarOffHint' ),
		'lightbox_section_toolbar' => array( 'group' => 'lightbox', 'key' => 'sectionToolbar' ),
		'lightbox_section_buttons' => array( 'group' => 'lightbox', 'key' => 'sectionButtons' ),
		'lightbox_section_click' => array( 'group' => 'lightbox', 'key' => 'sectionClick' ),
		'lightbox_section_motion' => array( 'group' => 'lightbox', 'key' => 'sectionMotion' ),
		'lightbox_section_display' => array( 'group' => 'lightbox', 'key' => 'sectionDisplay' ),
		'lightbox_close' => array( 'group' => 'lightbox', 'key' => 'close' ),
		'lightbox_thumbs' => array( 'group' => 'lightbox', 'key' => 'thumbs' ),
		'lightbox_download' => array( 'group' => 'lightbox', 'key' => 'download' ),
		'lightbox_zoom' => array( 'group' => 'lightbox', 'key' => 'zoom' ),
		'lightbox_share' => array( 'group' => 'lightbox', 'key' => 'share' ),
		'lightbox_clickSlide' => array( 'group' => 'lightbox', 'key' => 'clickSlide' ),
		'lightbox_infobar' => array( 'group' => 'lightbox', 'key' => 'infobar' ),
		'lightbox_animationEffect' => array( 'group' => 'lightbox', 'key' => 'animationEffect' ),
		'lightbox_transitionEffect' => array( 'group' => 'lightbox', 'key' => 'transitionEffect' ),
		'showAllOnLightbox' => array( 'group' => 'lightbox', 'key' => 'showAll' ),
		'lightbox_touch' => array( 'group' => 'lightbox', 'key' => 'touch' ),
		'lightbox_thumbsAutoStart' => array( 'group' => 'lightbox', 'key' => 'showThumbnails' ),
		'lightbox_background_color' => array( 'group' => 'lightbox', 'key' => 'backgroundColor' ),
		'lightbox_thumbsPosition' => array( 'group' => 'lightbox', 'key' => 'thumbsPosition' ),
		'download_all_lightbox_button' => array( 'group' => 'lightbox', 'key' => 'downloadAllButton' ),
		'enable_fullscreen' => array( 'group' => 'lightbox', 'key' => 'enableFullscreen' ),
		'open_fullscreen' => array( 'group' => 'lightbox', 'key' => 'openFullscreen' ),
		'hide_title' => array( 'group' => 'captions', 'key' => 'hideTitle' ),
		'titleColor' => array( 'group' => 'captions', 'key' => 'titleColor' ),
		'titleFontSize' => array( 'group' => 'captions', 'key' => 'titleFontSize' ),
		'mobileTitleFontSize' => array( 'group' => 'captions', 'key' => 'mobileTitleFontSize' ),
		'hide_description' => array( 'group' => 'captions', 'key' => 'hideDescription' ),
		'captionColor' => array( 'group' => 'captions', 'key' => 'captionColor' ),
		'captionFontSize' => array( 'group' => 'captions', 'key' => 'captionFontSize' ),
		'mobileCaptionFontSize' => array( 'group' => 'captions', 'key' => 'mobileCaptionFontSize' ),
		'show_gallery_title' => array( 'group' => 'captions', 'key' => 'hideGalleryTitle' ),
		'gallery_title_type' => array( 'group' => 'captions', 'key' => 'galleryTitleType' ),
		'titleFontWeight' => array( 'group' => 'captions', 'key' => 'titleFontWeight' ),
		'captionFontWeight' => array( 'group' => 'captions', 'key' => 'captionFontWeight' ),
		'mobile_caption_copy' => array( 'group' => 'captions', 'key' => 'mobileCaptionCopy' ),
		'contentPlacement' => array( 'group' => 'captions', 'key' => 'contentPlacement' ),
		'compact_caption_popover' => array( 'group' => 'captions', 'key' => 'compactCaptionPopover' ),
		'compact_caption_min_size' => array( 'group' => 'captions', 'key' => 'compactCaptionMinSize' ),
		'belowImageAlignment' => array( 'group' => 'captions', 'key' => 'belowImageAlignment' ),
		'belowImageSpacing' => array( 'group' => 'captions', 'key' => 'belowImageSpacing' ),
		'belowImagePadding' => array( 'group' => 'captions', 'key' => 'belowImagePadding' ),
		'captions_section_what_shows' => array( 'group' => 'captions', 'key' => 'sectionWhatShows' ),
		'captions_section_placement' => array( 'group' => 'captions', 'key' => 'sectionPlacement' ),
		'captions_section_title_style' => array( 'group' => 'captions', 'key' => 'sectionTitleStyle' ),
		'captions_section_caption_style' => array( 'group' => 'captions', 'key' => 'sectionCaptionStyle' ),
		'captions_section_on_mobile' => array( 'group' => 'captions', 'key' => 'sectionOnMobile' ),
		'enableSocial' => array( 'group' => 'social', 'key' => 'enableSocial' ),
		'social_section_where_they_can_share' => array( 'group' => 'social', 'key' => 'sectionWhereTheyCanShare' ),
		'enableTwitter' => array( 'group' => 'social', 'key' => 'enableTwitter' ),
		'enableFacebook' => array( 'group' => 'social', 'key' => 'enableFacebook' ),
		'enableWhatsapp' => array( 'group' => 'social', 'key' => 'enableWhatsapp' ),
		'enableLinkedin' => array( 'group' => 'social', 'key' => 'enableLinkedin' ),
		'enablePinterest' => array( 'group' => 'social', 'key' => 'enablePinterest' ),
		'enableEmail' => array( 'group' => 'social', 'key' => 'enableEmail' ),
		'emailSubject' => array( 'group' => 'social', 'key' => 'emailSubject' ),
		'emailMessage' => array( 'group' => 'social', 'key' => 'emailMessage' ),
		'social_section_how_buttons_look' => array( 'group' => 'social', 'key' => 'sectionHowButtonsLook' ),
		'socialIconColor' => array( 'group' => 'social', 'key' => 'socialIconColor' ),
		'socialIconSize' => array( 'group' => 'social', 'key' => 'socialIconSize' ),
		'socialIconPadding' => array( 'group' => 'social', 'key' => 'socialIconPadding' ),
		'socialDesktopCollapsed' => array( 'group' => 'social', 'key' => 'socialDesktopCollapsed' ),
		'social_no_network_style_hint' => array( 'group' => 'social', 'key' => 'noNetworkStyleHint' ),
		'sectionMotion' => array( 'group' => 'loadingEffects', 'key' => 'sectionMotion' ),
		'enableScale' => array( 'group' => 'loadingEffects', 'key' => 'enableScale' ),
		'loadedScale' => array( 'group' => 'loadingEffects', 'key' => 'loadedScale' ),
		'enableRotate' => array( 'group' => 'loadingEffects', 'key' => 'enableRotate' ),
		'loadedRotate' => array( 'group' => 'loadingEffects', 'key' => 'loadedRotate' ),
		'enableSlide' => array( 'group' => 'loadingEffects', 'key' => 'enableSlide' ),
		'loadedHSlide' => array( 'group' => 'loadingEffects', 'key' => 'loadedHSlide' ),
		'loadedVSlide' => array( 'group' => 'loadingEffects', 'key' => 'loadedVSlide' ),
		'inView' => array( 'group' => 'loadingEffects', 'key' => 'inView' ),
		'hover_builder' => array( 'group' => 'hover', 'key' => 'builder' ),
		'hover_effect_builder' => array( 'group' => 'hover', 'key' => 'effectBuilder' ),
		'hover_section_presets' => array( 'group' => 'hover', 'key' => 'sectionPresets' ),
		'hover_section_cursor' => array( 'group' => 'hover', 'key' => 'sectionCursor' ),
		'hover_section_overlay' => array( 'group' => 'hover', 'key' => 'sectionOverlay' ),
		'cursor' => array( 'group' => 'hover', 'key' => 'cursor' ),
		'change_cursor' => array( 'group' => 'hover', 'key' => 'changeCursor' ),
		'uploadCursor' => array( 'group' => 'hover', 'key' => 'uploadCursor' ),
		'dimOverlay' => array( 'group' => 'hover', 'key' => 'dimOverlay' ),
		'hoverColor' => array( 'group' => 'hover', 'key' => 'hoverColor' ),
		'hoverOpacity' => array( 'group' => 'hover', 'key' => 'hoverOpacity' ),
		'respect_reduced_motion' => array( 'group' => 'interaction', 'key' => 'respectReducedMotion' ),
		'borderSize' => array( 'group' => 'style', 'key' => 'borderSize' ),
		'borderRadius' => array( 'group' => 'style', 'key' => 'borderRadius' ),
		'borderColor' => array( 'group' => 'style', 'key' => 'borderColor' ),
		'shadowSize' => array( 'group' => 'style', 'key' => 'shadowSize' ),
		'shadowColor' => array( 'group' => 'style', 'key' => 'shadowColor' ),
		'style_section_frame' => array( 'group' => 'style', 'key' => 'sectionFrame' ),
		'style_section_custom_css' => array( 'group' => 'style', 'key' => 'sectionCustomCss' ),
		'lazy_load' => array( 'group' => 'performance', 'key' => 'lazyLoad' ),
		'performance_section_loading' => array( 'group' => 'performance', 'key' => 'sectionLoading' ),
		'performance_section_files' => array( 'group' => 'performance', 'key' => 'sectionFiles' ),
		'enable_optimization' => array( 'group' => 'performance', 'key' => 'enableOptimization' ),
		'thumbnail_optimization' => array( 'group' => 'performance', 'key' => 'thumbnailOptimization' ),
		'lightbox_optimization' => array( 'group' => 'performance', 'key' => 'lightboxOptimization' ),
		'modula_speed_help' => array( 'group' => 'performance', 'key' => 'modulaSpeedHelp' ),
		'performance_speedup_global_note' => array( 'group' => 'performance', 'key' => 'speedupGlobalNote' ),
		'enable_responsive' => array( 'group' => 'responsive', 'key' => 'enableResponsive' ),
		'tablet_columns' => array( 'group' => 'responsive', 'key' => 'tabletColumns' ),
		'mobile_columns' => array( 'group' => 'responsive', 'key' => 'mobileColumns' ),
		'treat_as_tablet_under' => array( 'group' => 'responsive', 'key' => 'treatAsTabletUnder' ),
		'treat_as_phone_under' => array( 'group' => 'responsive', 'key' => 'treatAsPhoneUnder' ),
		'slider_section_image' => array( 'group' => 'slider', 'key' => 'sectionImage' ),
		'slider_section_slides' => array( 'group' => 'slider', 'key' => 'sectionSlides' ),
		'slider_section_navigation' => array( 'group' => 'slider', 'key' => 'sectionNavigation' ),
		'slider_section_autoplay' => array( 'group' => 'slider', 'key' => 'sectionAutoplay' ),
		'slider_section_thumbnails' => array( 'group' => 'slider', 'key' => 'sectionThumbnails' ),
		'slider_lightbox' => array( 'group' => 'slider', 'key' => 'lightbox' ),
		'slider_image_size' => array( 'group' => 'slider', 'key' => 'imageSize' ),
		'slider_image_dimensions' => array( 'group' => 'slider', 'key' => 'imageDimensions' ),
		'slider_image_crop' => array( 'group' => 'slider', 'key' => 'imageCrop' ),
		'slider_adaptiveHeight' => array( 'group' => 'slider', 'key' => 'adaptiveHeight' ),
		'slider_syncing' => array( 'group' => 'slider', 'key' => 'syncing' ),
		'slider_syncing_nav_size' => array( 'group' => 'slider', 'key' => 'syncingNavSize' ),
		'slider_syncing_nav_image_dimensions' => array( 'group' => 'slider', 'key' => 'syncingNavImageDimensions' ),
		'slider_syncing_nav_image_crop' => array( 'group' => 'slider', 'key' => 'syncingNavImageCrop' ),
		'slider_syncing_nav_thumbnails_number' => array( 'group' => 'slider', 'key' => 'syncingNavThumbnailsNumber' ),
		'slider_syncing_nav_thumbnails_gutter' => array( 'group' => 'slider', 'key' => 'syncingNavThumbnailsGutter' ),
		'slider_syncing_nav_thumbnails_border_color' => array( 'group' => 'slider', 'key' => 'syncingNavThumbnailsBorderColor' ),
		'slider_autoplay' => array( 'group' => 'slider', 'key' => 'autoplay' ),
		'slider_autoplaySpeed' => array( 'group' => 'slider', 'key' => 'autoplaySpeed' ),
		'slider_pauseOnHover' => array( 'group' => 'slider', 'key' => 'pauseOnHover' ),
		'slider_arrows' => array( 'group' => 'slider', 'key' => 'arrows' ),
		'slider_arrows_inside' => array( 'group' => 'slider', 'key' => 'arrowsInside' ),
		'slider_dots' => array( 'group' => 'slider', 'key' => 'dots' ),
		'slider_draggable' => array( 'group' => 'slider', 'key' => 'draggable' ),
		'slider_centerMode' => array( 'group' => 'slider', 'key' => 'centerMode' ),
		'slider_centerPadding' => array( 'group' => 'slider', 'key' => 'centerPadding' ),
		'slider_fade' => array( 'group' => 'slider', 'key' => 'fade' ),
		'slider_infinite' => array( 'group' => 'slider', 'key' => 'infinite' ),
		'story_infinite' => array( 'group' => 'story', 'key' => 'infinite' ),
		'showcase_section_layout' => array( 'group' => 'showcase', 'key' => 'sectionLayout' ),
		'showcase_visible_count' => array( 'group' => 'showcase', 'key' => 'visibleCount' ),
		'showcase_gap' => array( 'group' => 'showcase', 'key' => 'gap' ),
		'showcase_center_scale' => array( 'group' => 'showcase', 'key' => 'centerScale' ),
		'showcase_center_bias' => array( 'group' => 'showcase', 'key' => 'centerBias' ),
		'showcase_arrow_position' => array( 'group' => 'showcase', 'key' => 'arrowPosition' ),
		'showcase_autoplay' => array( 'group' => 'showcase', 'key' => 'autoplay' ),
		'showcase_autoplay_interval' => array( 'group' => 'showcase', 'key' => 'autoplayInterval' ),
		'showcase_click_behavior' => array( 'group' => 'showcase', 'key' => 'clickBehavior' ),
		'showcase_mobile_simplify' => array( 'group' => 'showcase', 'key' => 'mobileSimplify' ),
		'template_section_layout' => array( 'group' => 'template', 'key' => 'sectionLayout' ),
		'template_layout' => array( 'group' => 'template', 'key' => 'templateLayout' ),
		'slider_slidesToShow' => array( 'group' => 'slider', 'key' => 'slidesToShow' ),
		/*
		 * Flat `slider_slidesToScroll` → grouped `slider.slidesToScroll`.
		 * React slider reads this via sliderSettingsToCarousel → navigationStepBySlide
		 * when the step differs from slidesToShow (SliderLayout patchStepNavigation).
		 */
		'slider_slidesToScroll' => array( 'group' => 'slider', 'key' => 'slidesToScroll' ),
		'slider_speed' => array( 'group' => 'slider', 'key' => 'speed' ),
		'slider_rtl' => array( 'group' => 'slider', 'key' => 'rtl' ),
		'slider_initialSlide' => array( 'group' => 'slider', 'key' => 'initialSlide' ),
		'slider_image_info' => array( 'group' => 'slider', 'key' => 'imageInfo' ),
		'slider_image_info_position' => array( 'group' => 'slider', 'key' => 'imageInfoPosition' ),
		'slider_tablet_slides' => array( 'group' => 'slider', 'key' => 'tabletSlides' ),
		'slider_tablet_scrolls' => array( 'group' => 'slider', 'key' => 'tabletScrolls' ),
		'slider_mobile_slides' => array( 'group' => 'slider', 'key' => 'mobileSlides' ),
		'slider_mobile_scrolls' => array( 'group' => 'slider', 'key' => 'mobileScrolls' ),
		'maxImagesCount' => array( 'group' => 'pagination', 'key' => 'maxImagesCount' ),
		'maxImagesCount_mobile' => array( 'group' => 'pagination', 'key' => 'maxImagesCountMobile' ),
		'enable_pagination' => array( 'group' => 'pagination', 'key' => 'enablePagination' ),
		'enable_infinite_scroll' => array( 'group' => 'pagination', 'key' => 'enableInfiniteScroll' ),
		'enable_load_more' => array( 'group' => 'pagination', 'key' => 'enableLoadMore' ),
		'pagination_number' => array( 'group' => 'pagination', 'key' => 'paginationNumber' ),
		'pagination_color' => array( 'group' => 'pagination', 'key' => 'paginationColor' ),
		'active_pagination_color' => array( 'group' => 'pagination', 'key' => 'activePaginationColor' ),
		'pagination_position' => array( 'group' => 'pagination', 'key' => 'paginationPosition' ),
		'filters' => array( 'group' => 'filters', 'key' => 'filters' ),
		'show_filter_bar' => array( 'group' => 'filters', 'key' => 'showFilterBar' ),
		'filters_section_filters_list' => array( 'group' => 'filters', 'key' => 'sectionFiltersList' ),
		'filters_section_all_label' => array( 'group' => 'filters', 'key' => 'sectionAllLabel' ),
		'dropdownFilters' => array( 'group' => 'filters', 'key' => 'dropdownFilters' ),
		'filterClick' => array( 'group' => 'filters', 'key' => 'filterClick' ),
		'hideAllFilter' => array( 'group' => 'filters', 'key' => 'hideAllFilter' ),
		'showFilterCount' => array( 'group' => 'filters', 'key' => 'showFilterCount' ),
		'allFilterLabel' => array( 'group' => 'filters', 'key' => 'allFilterLabel' ),
		'filterLinkColor' => array( 'group' => 'filters', 'key' => 'filterLinkColor' ),
		'filterLinkHoverColor' => array( 'group' => 'filters', 'key' => 'filterLinkHoverColor' ),
		'defaultActiveFilter' => array( 'group' => 'filters', 'key' => 'defaultActiveFilter' ),
		'filterPositioning' => array( 'group' => 'filters', 'key' => 'filterPositioning' ),
		'filterTextAlignment' => array( 'group' => 'filters', 'key' => 'filterTextAlignment' ),
		'enableCollapsibleFilters' => array( 'group' => 'filters', 'key' => 'enableCollapsibleFilters' ),
		'collapsibleActionText' => array( 'group' => 'filters', 'key' => 'collapsibleActionText' ),
		'enableMobileDropdownFilters' => array( 'group' => 'filters', 'key' => 'enableMobileDropdownFilters' ),
		'modula_deeplink' => array( 'group' => 'deeplink', 'key' => 'modulaDeeplink' ),
		'deeplink_off_hint' => array( 'group' => 'deeplink', 'key' => 'modulaDeeplinkOffHint' ),
		'customLinkName' => array( 'group' => 'deeplink', 'key' => 'customLinkName' ),
		'deeplink_url_preview' => array( 'group' => 'deeplink', 'key' => 'urlPreview' ),
		'enable_password' => array( 'group' => 'passwordProtect', 'key' => 'enablePassword' ),
		'password_protect_section_password_form' => array( 'group' => 'passwordProtect', 'key' => 'sectionPasswordForm' ),
		'password' => array( 'group' => 'passwordProtect', 'key' => 'password' ),
		'password_protect_username' => array( 'group' => 'passwordProtect', 'key' => 'passwordProtectUsername' ),
		'password_protect_text' => array( 'group' => 'passwordProtect', 'key' => 'passwordProtectText' ),
		'enable_slideshow' => array( 'group' => 'slideshow', 'key' => 'enableSlideshow' ),
		'slideshow_section_slideshow' => array( 'group' => 'slideshow', 'key' => 'sectionSlideshow' ),
		'slideshow_section_playback' => array( 'group' => 'slideshow', 'key' => 'sectionPlayback' ),
		'enable_autoplay' => array( 'group' => 'slideshow', 'key' => 'enableAutoplay' ),
		'pause_on_hover' => array( 'group' => 'slideshow', 'key' => 'pauseOnHover' ),
		'slideshow_speed' => array( 'group' => 'slideshow', 'key' => 'slideshowSpeed' ),
		'autoplay-videos' => array( 'group' => 'video', 'key' => 'autoplayVideos' ),
		'loop-videos' => array( 'group' => 'video', 'key' => 'loopVideos' ),
		'show-video-icon' => array( 'group' => 'video', 'key' => 'showVideoIcon' ),
		'use-custom-icon' => array( 'group' => 'video', 'key' => 'useCustomIcon' ),
		'custom-video-icon' => array( 'group' => 'video', 'key' => 'customVideoIcon' ),
		'video-icon-icon' => array( 'group' => 'video', 'key' => 'videoIconIcon' ),
		'video-icon-color' => array( 'group' => 'video', 'key' => 'videoIconColor' ),
		'play-icon-size' => array( 'group' => 'video', 'key' => 'playIconSize' ),
		'preview-video' => array( 'group' => 'video', 'key' => 'previewVideo' ),
		'preview-video-duration' => array( 'group' => 'video', 'key' => 'previewVideoDuration' ),
		'autoplay_thumbnail' => array( 'group' => 'video', 'key' => 'autoplayThumbnail' ),
		'preview_video_off_hint' => array( 'group' => 'video', 'key' => 'previewVideoOffHint' ),
		'playlist_position' => array( 'group' => 'video', 'key' => 'playlistPosition' ),
		'protection' => array( 'group' => 'protection', 'key' => 'protection' ),
		'protection_section_basics' => array( 'group' => 'protection', 'key' => 'sectionBasics' ),
		'right_click_message' => array( 'group' => 'protection', 'key' => 'rightClickMessage' ),
		'block_dragging' => array( 'group' => 'protection', 'key' => 'blockDragging' ),
		'protection_section_harder_measures' => array( 'group' => 'protection', 'key' => 'sectionHarderMeasures' ),
		'blur_protection' => array( 'group' => 'protection', 'key' => 'blurProtection' ),
		'url_protection' => array( 'group' => 'protection', 'key' => 'urlProtection' ),
		'protection_url_cost_hint' => array( 'group' => 'protection', 'key' => 'urlProtectionCostHint' ),
		'enable_download' => array( 'group' => 'download', 'key' => 'enableDownload' ),
		'download_section_what_they_can_take' => array( 'group' => 'download', 'key' => 'sectionWhatTheyCanTake' ),
		'download_gallery_button' => array( 'group' => 'download', 'key' => 'downloadGalleryButton' ),
		'download_all_gallery_button' => array( 'group' => 'download', 'key' => 'downloadAllGalleryButton' ),
		'download_image_sizes' => array( 'group' => 'download', 'key' => 'downloadImageSizes' ),
		'download_section_gallery_button' => array( 'group' => 'download', 'key' => 'sectionGalleryButton' ),
		'download_all_label' => array( 'group' => 'download', 'key' => 'downloadAllLabel' ),
		'download_all_position' => array( 'group' => 'download', 'key' => 'downloadAllPosition' ),
		'download_all_hposition' => array( 'group' => 'download', 'key' => 'downloadAllHposition' ),
		'download_section_how_it_looks' => array( 'group' => 'download', 'key' => 'sectionHowItLooks' ),
		'download_all_color' => array( 'group' => 'download', 'key' => 'downloadAllColor' ),
		'download_all_background_color' => array( 'group' => 'download', 'key' => 'downloadAllBackgroundColor' ),
		'download_all_gallery_button_icon' => array( 'group' => 'download', 'key' => 'downloadAllGalleryButtonIcon' ),
		'download_all_gallery_icon_color' => array( 'group' => 'download', 'key' => 'downloadAllGalleryIconColor' ),
		'download_section_zip_name' => array( 'group' => 'download', 'key' => 'sectionZipName' ),
		'custom_zip_name' => array( 'group' => 'download', 'key' => 'customZipName' ),
		'enable_zoom' => array( 'group' => 'zoom', 'key' => 'enableZoom' ),
		'zoom_section_style' => array( 'group' => 'zoom', 'key' => 'sectionStyle' ),
		'zoom_on_hover' => array( 'group' => 'zoom', 'key' => 'zoomOnHover' ),
		'zoom_type' => array( 'group' => 'zoom', 'key' => 'zoomType' ),
		'zoom_effect' => array( 'group' => 'zoom', 'key' => 'zoomEffect' ),
		'zoom_section_magnified_window' => array( 'group' => 'zoom', 'key' => 'sectionMagnifiedWindow' ),
		'zoom_magnified_window_hint' => array( 'group' => 'zoom', 'key' => 'magnifiedWindowHint' ),
		'zoom_window_position' => array( 'group' => 'zoom', 'key' => 'zoomWindowPosition' ),
		'zoom_window_size' => array( 'group' => 'zoom', 'key' => 'zoomWindowSize' ),
		'zoom_lens_size' => array( 'group' => 'zoom', 'key' => 'zoomLensSize' ),
		'zoom_lens_shape' => array( 'group' => 'zoom', 'key' => 'zoomLensShape' ),
		'zoom_section_tint' => array( 'group' => 'zoom', 'key' => 'sectionTint' ),
		'zoom_tint_color' => array( 'group' => 'zoom', 'key' => 'zoomTintColor' ),
		'zoom_tint_opacity' => array( 'group' => 'zoom', 'key' => 'zoomTintOpacity' ),
		'enable_watermark' => array( 'group' => 'watermark', 'key' => 'enableWatermark' ),
		'watermark_type' => array( 'group' => 'watermark', 'key' => 'watermarkType' ),
		'custom_settings_watermark' => array( 'group' => 'watermark', 'key' => 'customSettingsWatermark' ),
		'watermark_section_text' => array( 'group' => 'watermark', 'key' => 'sectionText' ),
		'watermark_text' => array( 'group' => 'watermark', 'key' => 'watermarkText' ),
		'watermark_text_size' => array( 'group' => 'watermark', 'key' => 'watermarkTextSize' ),
		'watermark_text_color' => array( 'group' => 'watermark', 'key' => 'watermarkTextColor' ),
		'watermark_text_type_hint' => array( 'group' => 'watermark', 'key' => 'watermarkTextTypeHint' ),
		'watermark_section_image' => array( 'group' => 'watermark', 'key' => 'sectionImage' ),
		'watermark_image' => array( 'group' => 'watermark', 'key' => 'watermarkImage' ),
		'watermark_image_dimension_width' => array( 'group' => 'watermark', 'key' => 'watermarkImageDimensionWidth' ),
		'watermark_image_type_hint' => array( 'group' => 'watermark', 'key' => 'watermarkImageTypeHint' ),
		'watermark_image_dimension_height' => array( 'group' => 'watermark', 'key' => 'watermarkImageDimensionHeight' ),
		'watermark_section_placement' => array( 'group' => 'watermark', 'key' => 'sectionPlacement' ),
		'watermark_position' => array( 'group' => 'watermark', 'key' => 'watermarkPosition' ),
		'watermark_margin' => array( 'group' => 'watermark', 'key' => 'watermarkMargin' ),
		'watermark_opacity' => array( 'group' => 'watermark', 'key' => 'watermarkOpacity' ),
		'watermark_section_applies_to' => array( 'group' => 'watermark', 'key' => 'sectionAppliesTo' ),
		'watermark_apply_scope' => array( 'group' => 'watermark', 'key' => 'watermarkApplyScope' ),
		'watermark_enable_backup' => array( 'group' => 'watermark', 'key' => 'watermarkEnableBackup' ),
		'watermark_burn_in_hint' => array( 'group' => 'watermark', 'key' => 'watermarkBurnInHint' ),
		'watermark_apply_to_existing_images' => array( 'group' => 'watermark', 'key' => 'watermarkApplyToExistingImages' ),
		'watermark_remove_watermark' => array( 'group' => 'watermark', 'key' => 'watermarkRemoveWatermark' ),
		'enable_exif' => array( 'group' => 'exif', 'key' => 'enableExif' ),
		'exif_enable_off_hint' => array( 'group' => 'exif', 'key' => 'enableExifOffHint' ),
		'exif_camera' => array( 'group' => 'exif', 'key' => 'exifCamera' ),
		'exif_lens' => array( 'group' => 'exif', 'key' => 'exifLens' ),
		'exif_shutter_speed' => array( 'group' => 'exif', 'key' => 'exifShutterSpeed' ),
		'exif_aperture' => array( 'group' => 'exif', 'key' => 'exifAperture' ),
		'exif_focal_length' => array( 'group' => 'exif', 'key' => 'exifFocalLength' ),
		'exif_iso' => array( 'group' => 'exif', 'key' => 'exifIso' ),
		'exif_date' => array( 'group' => 'exif', 'key' => 'exifDate' ),
		'exif_section_result' => array( 'group' => 'exif', 'key' => 'sectionResult' ),
		'exif_result_preview' => array( 'group' => 'exif', 'key' => 'exifResultPreview' ),
		'exif_result_hint' => array( 'group' => 'exif', 'key' => 'exifResultHint' ),
		'licensing_section_license' => array( 'group' => 'licensing', 'key' => 'sectionLicense' ),
		'image_licensing' => array( 'group' => 'licensing', 'key' => 'imageLicensing' ),
		'image_licensing_author' => array( 'group' => 'licensing', 'key' => 'author' ),
		'image_licensing_company' => array( 'group' => 'licensing', 'key' => 'company' ),
		'licensing_section_where_it_shows' => array( 'group' => 'licensing', 'key' => 'sectionWhereItShows' ),
		'display_with_description' => array( 'group' => 'licensing', 'key' => 'displayWithDescription' ),
		'show_on_lightbox' => array( 'group' => 'licensing', 'key' => 'showOnLightbox' ),
		'comment_status' => array( 'group' => 'comments', 'key' => 'commentStatus' ),
		'comments_section_display' => array( 'group' => 'comments', 'key' => 'sectionDisplay' ),
		'toggle_comments' => array( 'group' => 'comments', 'key' => 'toggleComments' ),
		'start_collapsed' => array( 'group' => 'comments', 'key' => 'startCollapsed' ),
		'image_proofing' => array( 'group' => 'proofing', 'key' => 'imageProofing' ),
		'min_selection' => array( 'group' => 'proofing', 'key' => 'minSelection' ),
		'max_selection' => array( 'group' => 'proofing', 'key' => 'maxSelection' ),
		'proofing_notification_email' => array( 'group' => 'proofing', 'key' => 'notificationEmail' ),
		'login_rejection_notice' => array( 'group' => 'proofing', 'key' => 'loginRejectionNotice' ),
		'show_login_link' => array( 'group' => 'proofing', 'key' => 'showLoginLink' ),
		'expire_rejection_notice' => array( 'group' => 'proofing', 'key' => 'expireRejectionNotice' ),
		'expire_link_to_page' => array( 'group' => 'proofing', 'key' => 'expireLinkToPage' ),
		'expire_link_to_page_url' => array( 'group' => 'proofing', 'key' => 'expireLinkToPageUrl' ),
		'syncWithInstagram' => array( 'group' => 'instagram', 'key' => 'syncWithInstagram' ),
		'instagram_account_panel' => array( 'group' => 'instagram', 'key' => 'accountPanel' ),
		'instagram_manage_photos' => array( 'group' => 'instagram', 'key' => 'managePhotos' ),
		'instagram_cron_note' => array( 'group' => 'instagram', 'key' => 'cronNote' ),
		'export_import_section_presets' => array( 'group' => 'exportImport', 'key' => 'sectionPresets' ),
		'export_import_gallery_defaults_panel' => array( 'group' => 'exportImport', 'key' => 'galleryDefaultsPanel' ),
		'export_import_tools_note' => array( 'group' => 'exportImport', 'key' => 'toolsNote' ),
		'polaroid_rotation_max' => array( 'group' => 'polaroid', 'key' => 'rotationMax' ),
		'polaroid_scatter_max' => array( 'group' => 'polaroid', 'key' => 'scatterMax' ),
		'polaroid_show_pin' => array( 'group' => 'polaroid', 'key' => 'showPin' ),
		'polaroid_frame_padding' => array( 'group' => 'polaroid', 'key' => 'framePadding' ),
		'polaroid_chin_height' => array( 'group' => 'polaroid', 'key' => 'chinHeight' ),
		'polaroid_uniform_size' => array( 'group' => 'polaroid', 'key' => 'uniformSize' ),
		'polaroid_uniform_columns' => array( 'group' => 'polaroid', 'key' => 'uniformColumns' ),
		'polaroid_random_factor' => array( 'group' => 'polaroid', 'key' => 'randomFactor' ),
		'style' => array( 'group' => 'style', 'key' => 'customCss' ),
	);
	// phpcs:enable WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound, WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned

	/**
	 * @return array<string, array{group: string, key: string}>
	 */
	public static function get_flat_to_grouped_mapping() {
		return self::$flat_to_grouped;
	}
}
